version: '3.8'
services:
  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: mosquitto
    ports:
      - "1883:1883"    # MQTT
      - "9001:9001"    # MQTT over Websockets (для клієнтів, що підтримують websockets)
    volumes:
      # Mount the whole broker folder (safer on Windows) so Mosquitto can access the config and data
      - ./broker:/mosquitto/config
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log

  web1:
    build:
      context: ./web1
    container_name: web-service-1
    ports:
      - "5001:5000"    # внутрішній Flask на 5000 -> хост 5001
    depends_on:
      - mosquitto

  web2:
    build:
      context: ./web2
    container_name: web-service-2
    ports:
      - "5002:5000"    # внутрішній Flask на 5000 -> хост 5002
    depends_on:
      - mosquitto

volumes:
  mosquitto_data:
  mosquitto_log:
